import os
import sys
import json
import argparse

CONFIG_FILE = "scadable.json"
METADATA_FILE = ".scadable"

# ─── Templates ────────────────────────────────────────────────────────────────

MODBUS_TCP_TEMPLATE = '''\
"""
Generated by Scadable CLI.

Only modify the variable values below (host, port, slave_id, frequency, etc).
Do not rename classes or change the structure — the runtime depends on it.
"""
from scadable.edge import Device, ModbusConnection
from scadable.edge.constants import MODBUS_TCP, FIVE_SEC
from dataclasses import dataclass


@dataclass
class Connection(ModbusConnection):
    """
    Modbus TCP connection settings.

    Attributes:
        host: IP address or hostname of the Modbus device.
              Use "${{DEVICE_HOST}}" for environment variable injection.
        port: TCP port number (default: 502 for Modbus).
        slave_id: Modbus slave/unit ID (1-247).
    """
    host: str = "${{DEVICE_HOST}}"
    port: int = 502
    slave_id: int = 1


class {class_name}(Device):
    """
    Device configuration.

    Attributes:
        id: Unique identifier for this device.
        protocol: Communication protocol (MODBUS_TCP).
        connection: Connection settings class.
        frequency: Polling interval in seconds (how often to read data).
        filter: List of register names to pull (empty = pull all).
    """
    id = "{device_id}"
    protocol = MODBUS_TCP
    connection = Connection
    frequency = FIVE_SEC
    filter = []  # empty = pull all registers; e.g. ["reg_100", "reg_102"] to filter
'''

MODBUS_RTU_TEMPLATE = '''\
"""
Generated by Scadable CLI.

Only modify the variable values below (serial_port, baudrate, slave_id, etc).
Do not rename classes or change the structure — the runtime depends on it.
"""
from scadable.edge import Device, ModbusConnection
from scadable.edge.constants import MODBUS_RTU, FIVE_SEC
from dataclasses import dataclass


@dataclass
class Connection(ModbusConnection):
    """
    Modbus RTU (serial) connection settings.

    Attributes:
        serial_port: Serial port path (e.g., "/dev/ttyUSB0" on Linux,
                     "COM3" on Windows).
        slave_id: Modbus slave/unit ID (1-247).
        baudrate: Serial baud rate (common: 9600, 19200, 38400, 115200).
        parity: Parity bit — "N" (none), "E" (even), or "O" (odd).
        stopbits: Number of stop bits (1 or 2).
        bytesize: Data bits per byte (typically 8).
    """
    serial_port: str = "/dev/ttyUSB0"
    slave_id: int = 1
    baudrate: int = 9600
    parity: str = "N"
    stopbits: int = 1
    bytesize: int = 8


class {class_name}(Device):
    """
    Device configuration.

    Attributes:
        id: Unique identifier for this device.
        protocol: Communication protocol (MODBUS_RTU).
        connection: Connection settings class.
        frequency: Polling interval in seconds (how often to read data).
        filter: List of register names to pull (empty = pull all).
    """
    id = "{device_id}"
    protocol = MODBUS_RTU
    connection = Connection
    frequency = FIVE_SEC
    filter = []  # empty = pull all registers; e.g. ["reg_100", "reg_102"] to filter
'''

TEMPLATES = {
    "modbus-tcp": MODBUS_TCP_TEMPLATE,
    "modbus-rtu": MODBUS_RTU_TEMPLATE,
}

SCADABLE_ASCII = """
 ____     ____      _      ____       _      ____    _       _____
/ ___|   / ___|    / \\    |  _ \\     / \\    | __ )  | |     | ____|
\\___ \\  | |       / _ \\   | | | |   / _ \\   |  _ \\  | |     |  _|
 ___) | | |___   / ___ \\  | |_| |  / ___ \\  | |_) | | |___  | |___
|____/   \\____| /_/   \\_\\ |____/  /_/   \\_\\ |____/  |_____| |_____|

Edge SDK v0.2.0
"""

# ─── Helpers ──────────────────────────────────────────────────────────────────

def to_class_name(name: str) -> str:
    return "".join(p.capitalize() for p in name.replace("_", "-").split("-"))

def is_project():
    """Check if current directory is a Scadable project."""
    return os.path.exists(CONFIG_FILE) or os.path.exists(METADATA_FILE)

def require_project():
    """Exit if not in a Scadable project."""
    if not is_project():
        print(f"Not a Scadable project. Run 'scadable init' or clone from the dashboard.")
        sys.exit(1)

def load_project_config():
    """Load scadable.json if it exists."""
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE) as f:
            return json.load(f)
    return {}

def load_metadata():
    """Load .scadable metadata if it exists."""
    if os.path.exists(METADATA_FILE):
        with open(METADATA_FILE) as f:
            return json.load(f)
    return {}

# ─── Commands ─────────────────────────────────────────────────────────────────

def cmd_init(project_name: str = None):
    if is_project():
        config = load_project_config()
        name = config.get("project", os.path.basename(os.getcwd()))
        print(f"✓ Already a Scadable project: {name}")
        os.makedirs("devices", exist_ok=True)
        print(f"\nRun: scadable add device modbus-tcp <device-name>")
        return

    name = project_name or os.path.basename(os.getcwd())
    config = {"project": name, "version": "0.1.0"}
    os.makedirs("devices", exist_ok=True)
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)
    print(SCADABLE_ASCII)
    print(f"✓ Initialized project '{name}'")
    print(f"✓ Created devices/")
    print(f"✓ Created {CONFIG_FILE}")
    print(f"\nNext: scadable add device modbus-tcp <device-name>")

def cmd_add_device(protocol: str, device_name: str):
    require_project()
    template = TEMPLATES.get(protocol)
    if not template:
        print(f"Unknown protocol '{protocol}'. Available: {', '.join(TEMPLATES.keys())}")
        sys.exit(1)

    os.makedirs("devices", exist_ok=True)
    device_path = os.path.join("devices", device_name)
    if os.path.exists(device_path):
        print(f"Device '{device_name}' already exists.")
        sys.exit(1)

    os.makedirs(device_path)
    config_path = os.path.join(device_path, "config.py")
    content = template.format(
        class_name=to_class_name(device_name),
        device_id=device_name,
    )
    with open(config_path, "w") as f:
        f.write(content)
    print(f"✓ Created {config_path}")
    print(f"\nNext: edit {config_path} and set your connection details.")

def cmd_list_devices():
    """List all devices in the project."""
    require_project()
    devices_dir = "devices"
    if not os.path.exists(devices_dir):
        print("No devices found.")
        return

    devices = []
    for name in sorted(os.listdir(devices_dir)):
        path = os.path.join(devices_dir, name)
        if os.path.isdir(path) and os.path.exists(os.path.join(path, "config.py")):
            devices.append(name)

    if not devices:
        print("No devices found. Run: scadable add device modbus-tcp <name>")
        return

    config = load_project_config()
    print(f"Project: {config.get('project', 'unknown')}")
    print(f"Devices ({len(devices)}):")
    for d in devices:
        print(f"  • {d}")

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="scadable",
        description="Scadable Edge SDK — manage IoT device configurations"
    )
    sub = parser.add_subparsers(dest="command")

    # scadable init [name]
    p_init = sub.add_parser("init", help="Initialize a new Scadable project")
    p_init.add_argument("name", nargs="?", help="Project name (default: current folder name)")

    # scadable add device <protocol> <name>
    p_add = sub.add_parser("add", help="Add a device")
    add_sub = p_add.add_subparsers(dest="resource")

    p_dev = add_sub.add_parser("device", help="Add a new device")
    p_dev.add_argument("protocol", choices=list(TEMPLATES.keys()), help="Device protocol")
    p_dev.add_argument("name", help="Device name e.g. temp-sensor")

    # scadable list
    sub.add_parser("list", help="List devices in the project")

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args.name)
    elif args.command == "add":
        if args.resource == "device":
            cmd_add_device(args.protocol, args.name)
        else:
            p_add.print_help()
    elif args.command == "list":
        cmd_list_devices()
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
