import os
import sys
import json
import argparse

CONFIG_FILE = "scadable.json"
METADATA_FILE = ".scadable"

# ─── Templates ────────────────────────────────────────────────────────────────

MODBUS_TCP_TEMPLATE = '''\
"""
Generated by Scadable CLI.

Only modify the variable values below (host, port, slave_id, frequency, etc).
Do not rename classes or change the structure — the runtime depends on it.
"""
from scadable.edge import Device, ModbusTCPConnection
from scadable.edge.constants import MODBUS_TCP, FIVE_SEC
from dataclasses import dataclass


@dataclass
class Connection(ModbusTCPConnection):
    """
    Modbus TCP connection settings.

    Attributes:
        host: IP address or hostname of the Modbus device.
              Use "${{DEVICE_HOST}}" for environment variable injection.
        port: TCP port number (default: 502 for Modbus).
        slave_id: Modbus slave/unit ID (1-247).
    """
    host: str = "${{DEVICE_HOST}}"
    port: int = 502
    slave_id: int = 1


class {class_name}(Device):
    """
    Modbus TCP device.

    Attributes:
        id: Unique identifier for this device.
        protocol: Communication protocol (MODBUS_TCP).
        connection: Connection settings class.
        frequency: Polling interval in seconds (how often to read data).
        filter: List of register names to pull (empty = pull all).
    """
    id = "{device_id}"
    protocol = MODBUS_TCP
    connection = Connection
    frequency = FIVE_SEC
    filter = []  # empty = pull all registers; e.g. ["reg_100", "reg_102"] to filter
'''

MODBUS_RTU_TEMPLATE = '''\
"""
Generated by Scadable CLI.

Only modify the variable values below (serial_port, baudrate, slave_id, etc).
Do not rename classes or change the structure — the runtime depends on it.
"""
from scadable.edge import Device, ModbusRTUConnection
from scadable.edge.constants import MODBUS_RTU, FIVE_SEC
from dataclasses import dataclass


@dataclass
class Connection(ModbusRTUConnection):
    """
    Modbus RTU (serial) connection settings.

    Attributes:
        serial_port: Serial port path (e.g., "/dev/ttyUSB0" on Linux,
                     "COM3" on Windows).
        slave_id: Modbus slave/unit ID (1-247).
        baudrate: Serial baud rate (common: 9600, 19200, 38400, 115200).
        parity: Parity bit — "N" (none), "E" (even), or "O" (odd).
        stopbits: Number of stop bits (1 or 2).
        bytesize: Data bits per byte (typically 8).
    """
    serial_port: str = "/dev/ttyUSB0"
    slave_id: int = 1
    baudrate: int = 9600
    parity: str = "N"
    stopbits: int = 1
    bytesize: int = 8


class {class_name}(Device):
    """
    Modbus RTU (serial) device.

    Attributes:
        id: Unique identifier for this device.
        protocol: Communication protocol (MODBUS_RTU).
        connection: Connection settings class.
        frequency: Polling interval in seconds (how often to read data).
        filter: List of register names to pull (empty = pull all).
    """
    id = "{device_id}"
    protocol = MODBUS_RTU
    connection = Connection
    frequency = FIVE_SEC
    filter = []  # empty = pull all registers; e.g. ["reg_100", "reg_102"] to filter
'''

OPCUA_TEMPLATE = '''\
"""
Generated by Scadable CLI.

Only modify the variable values below (host, port, node_ids, etc).
Do not rename classes or change the structure — the runtime depends on it.
"""
from scadable.edge import Device, OPCUAConnection
from scadable.edge.constants import OPCUA, FIVE_SEC
from dataclasses import dataclass, field
from typing import List


@dataclass
class Connection(OPCUAConnection):
    """
    OPC-UA connection settings.

    Connects to an OPC-UA server (Ignition, Kepware, Siemens, etc.)
    and reads the specified node values.

    Attributes:
        host: OPC-UA server hostname or IP address.
        port: OPC-UA server port (default: 4840).
        node_ids: List of OPC-UA node IDs to read.
                  String nodes: "ns=2;s=Temperature"
                  Numeric nodes: "ns=2;i=1001"
        security_policy: "None", "Basic256Sha256", or "Basic128Rsa15".
        username: Leave empty for anonymous access.
        password: Leave empty for anonymous access.
    """
    host: str = "${{OPCUA_HOST}}"
    port: int = 4840
    node_ids: List[str] = field(default_factory=lambda: [
        "ns=2;s=Temperature",
        "ns=2;s=Pressure",
    ])
    security_policy: str = "None"
    username: str = ""
    password: str = ""


class {class_name}(Device):
    """
    OPC-UA device.

    Reads data from an OPC-UA server. The gateway connects as a client
    and polls the configured node IDs at the specified frequency.

    Attributes:
        id: Unique identifier for this device.
        protocol: Communication protocol (OPCUA).
        connection: Connection settings class.
        frequency: Polling interval in seconds (how often to read data).
        filter: List of node names to include (empty = include all).
    """
    id = "{device_id}"
    protocol = OPCUA
    connection = Connection
    frequency = FIVE_SEC
    filter = []  # empty = read all node_ids; e.g. ["Temperature"] to filter
'''

SERIAL_TEMPLATE = '''\
"""
Generated by Scadable CLI.

Only modify the variable values below (serial_port, baudrate, etc).
Do not rename classes or change the structure — the runtime depends on it.
"""
from scadable.edge import Device, SerialDeviceConnection
from scadable.edge.constants import SERIAL, ONE_SEC
from dataclasses import dataclass


@dataclass
class Connection(SerialDeviceConnection):
    """
    Serial/UART device connection settings.

    Connects to a device over USB serial (ESP32, Arduino, sensors, etc).

    Attributes:
        serial_port: Serial port path.
                     Linux USB: "/dev/ttyUSB0" (CP2102/CH340) or "/dev/ttyACM0" (native USB).
                     macOS: "/dev/cu.usbserial-0001".
                     Windows: "COM3".
        baudrate: Serial baud rate.
                  115200 — default for most devices.
                  921600 — fast, recommended for image/binary transfer.
                  9600   — legacy sensors.
        parity: Parity bit — "N" (none), "E" (even), "O" (odd).
        stopbits: Number of stop bits (1 or 2).
        bytesize: Data bits per byte (typically 8).
    """
    serial_port: str = "/dev/ttyUSB0"
    baudrate: int = 115200
    parity: str = "N"
    stopbits: int = 1
    bytesize: int = 8


class {class_name}(Device):
    """
    Serial/UART device.

    Reads framed data from a serial device. The gateway opens the serial
    port and reads structured frames (with CRC validation) from the device.

    Attributes:
        id: Unique identifier for this device.
        protocol: Communication protocol (SERIAL).
        connection: Connection settings class.
        frequency: Polling interval in seconds (1 = real-time streaming).
        filter: List of data fields to include (empty = include all).
    """
    id = "{device_id}"
    protocol = SERIAL
    connection = Connection
    frequency = ONE_SEC
    filter = []  # empty = forward all data
'''

TEMPLATES = {
    "modbus-tcp": MODBUS_TCP_TEMPLATE,
    "modbus-rtu": MODBUS_RTU_TEMPLATE,
    "opcua": OPCUA_TEMPLATE,
    "serial": SERIAL_TEMPLATE,
}

SCADABLE_ASCII = """
 ____     ____      _      ____       _      ____    _       _____
/ ___|   / ___|    / \\    |  _ \\     / \\    | __ )  | |     | ____|
\\___ \\  | |       / _ \\   | | | |   / _ \\   |  _ \\  | |     |  _|
 ___) | | |___   / ___ \\  | |_| |  / ___ \\  | |_) | | |___  | |___
|____/   \\____| /_/   \\_\\ |____/  /_/   \\_\\ |____/  |_____| |_____|

Edge SDK v0.3.0
"""

# ─── Helpers ──────────────────────────────────────────────────────────────────

def to_class_name(name: str) -> str:
    return "".join(p.capitalize() for p in name.replace("_", "-").split("-"))

def is_project():
    """Check if current directory is a Scadable project."""
    return os.path.exists(CONFIG_FILE) or os.path.exists(METADATA_FILE)

def require_project():
    """Exit if not in a Scadable project."""
    if not is_project():
        print(f"Not a Scadable project. Run 'scadable init' or clone from the dashboard.")
        sys.exit(1)

def load_project_config():
    """Load scadable.json if it exists."""
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE) as f:
            return json.load(f)
    return {}

# ─── Commands ─────────────────────────────────────────────────────────────────

def cmd_init(project_name: str = None):
    if is_project():
        config = load_project_config()
        name = config.get("project", os.path.basename(os.getcwd()))
        print(f"Already a Scadable project: {name}")
        os.makedirs("devices", exist_ok=True)
        print(f"\nRun: scadable add device <protocol> <device-name>")
        return

    name = project_name or os.path.basename(os.getcwd())
    config = {"project": name, "version": "0.1.0"}
    os.makedirs("devices", exist_ok=True)
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)
    print(SCADABLE_ASCII)
    print(f"  Initialized project '{name}'")
    print(f"  Created devices/")
    print(f"  Created {CONFIG_FILE}")
    print(f"\n  Next: scadable add device <protocol> <name>")
    print(f"  Protocols: {', '.join(TEMPLATES.keys())}")

def cmd_add_device(protocol: str, device_name: str):
    require_project()
    template = TEMPLATES.get(protocol)
    if not template:
        print(f"Unknown protocol '{protocol}'. Available: {', '.join(TEMPLATES.keys())}")
        sys.exit(1)

    os.makedirs("devices", exist_ok=True)
    device_path = os.path.join("devices", device_name)
    if os.path.exists(device_path):
        print(f"Device '{device_name}' already exists.")
        sys.exit(1)

    os.makedirs(device_path)
    config_path = os.path.join(device_path, "config.py")
    content = template.format(
        class_name=to_class_name(device_name),
        device_id=device_name,
    )
    with open(config_path, "w") as f:
        f.write(content)
    print(f"  Created {config_path}")
    print(f"\n  Next: edit {config_path} and set your connection details.")

def cmd_list(resource: str = None):
    """List resources in the project."""
    require_project()

    if resource is None or resource == "devices":
        _list_dir("devices", "device")

    if resource is None or resource == "outbound":
        _list_dir("outbound", "outbound")

    if resource is None or resource == "storage":
        _list_dir("storage", "storage")

    if resource is None or resource == "decoders":
        _list_dir("decoders", "decoder")

def _list_dir(dirname: str, label: str):
    """List named resources in a directory."""
    if not os.path.exists(dirname):
        return

    items = []
    for name in sorted(os.listdir(dirname)):
        path = os.path.join(dirname, name)
        if os.path.isdir(path):
            items.append(name)

    if items:
        config = load_project_config()
        if label == "device":
            print(f"Project: {config.get('project', 'unknown')}")
        print(f"{label.capitalize()}s ({len(items)}):")
        for item in items:
            print(f"  {item}")

def cmd_validate():
    """Validate all project configs are correct and consistent."""
    require_project()
    config = load_project_config()
    errors = []
    warnings = []

    print(f"Validating project: {config.get('project', 'unknown')}")
    print()

    # Check devices
    devices_dir = "devices"
    device_ids = set()
    if os.path.exists(devices_dir):
        for name in sorted(os.listdir(devices_dir)):
            path = os.path.join(devices_dir, name)
            config_path = os.path.join(path, "config.py")

            if not os.path.isdir(path):
                continue

            if not os.path.exists(config_path):
                errors.append(f"Device '{name}' is missing config.py")
                continue

            # Try to parse the config
            try:
                with open(config_path) as f:
                    content = f.read()

                # Check for required patterns
                if "class " not in content or "(Device)" not in content:
                    errors.append(f"Device '{name}/config.py' — missing Device subclass")
                elif "connection" not in content.lower():
                    warnings.append(f"Device '{name}/config.py' — no connection settings found")
                else:
                    device_ids.add(name)
                    print(f"  device/{name} ... ok")
            except Exception as e:
                errors.append(f"Device '{name}/config.py' — {e}")
    else:
        warnings.append("No devices/ directory")

    # Check outbound
    outbound_dir = "outbound"
    if os.path.exists(outbound_dir):
        for name in sorted(os.listdir(outbound_dir)):
            path = os.path.join(outbound_dir, name)
            if os.path.isdir(path):
                print(f"  outbound/{name} ... ok")

    # Check decoders
    decoders_dir = "decoders"
    if os.path.exists(decoders_dir):
        for name in sorted(os.listdir(decoders_dir)):
            path = os.path.join(decoders_dir, name)
            if os.path.isdir(path):
                # Check for a script file
                has_script = any(
                    f.endswith(('.rhai', '.lua', '.py'))
                    for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))
                )
                if has_script:
                    print(f"  decoder/{name} ... ok")
                else:
                    warnings.append(f"Decoder '{name}' — no script file found (.rhai, .lua, .py)")

    # Check storage
    storage_dir = "storage"
    if os.path.exists(storage_dir):
        for name in sorted(os.listdir(storage_dir)):
            path = os.path.join(storage_dir, name)
            if os.path.isdir(path):
                print(f"  storage/{name} ... ok")

    # Print results
    print()
    if errors:
        print(f"Errors ({len(errors)}):")
        for e in errors:
            print(f"  {e}")
    if warnings:
        print(f"Warnings ({len(warnings)}):")
        for w in warnings:
            print(f"  {w}")

    if not errors and not warnings:
        print(f"All good. {len(device_ids)} device(s) configured.")
    elif not errors:
        print(f"\n{len(device_ids)} device(s) configured with {len(warnings)} warning(s).")
    else:
        print(f"\n{len(errors)} error(s) found. Fix them before deploying.")
        sys.exit(1)

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="scadable",
        description="Scadable Edge SDK — manage IoT device configurations"
    )
    sub = parser.add_subparsers(dest="command")

    # scadable init [name]
    p_init = sub.add_parser("init", help="Initialize a new Scadable project")
    p_init.add_argument("name", nargs="?", help="Project name (default: current folder name)")

    # scadable add <resource> <type> <name>
    p_add = sub.add_parser("add", help="Add a resource")
    add_sub = p_add.add_subparsers(dest="resource")

    p_dev = add_sub.add_parser("device", help="Add a new device")
    p_dev.add_argument("protocol", choices=list(TEMPLATES.keys()), help="Device protocol")
    p_dev.add_argument("name", help="Device name (e.g. my-plc, esp-32, ignition-server)")

    # scadable list [resource]
    p_list = sub.add_parser("list", help="List resources in the project")
    p_list.add_argument("resource", nargs="?",
                        choices=["devices", "outbound", "storage", "decoders"],
                        help="Resource type to list (default: all)")

    # scadable validate
    sub.add_parser("validate", help="Validate all project configs")

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args.name)
    elif args.command == "add":
        if args.resource == "device":
            cmd_add_device(args.protocol, args.name)
        else:
            p_add.print_help()
    elif args.command == "list":
        cmd_list(getattr(args, "resource", None))
    elif args.command == "validate":
        cmd_validate()
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
